#ifndef TOF_TABLE_LIB_H
#define TOF_TABLE_LIB_H

/* When compiled outside of McStas, provide minimal stubs for the types and
 * functions that the McStas runtime normally supplies. */
#ifndef MCSTAS
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

struct _struct_particle {
    double t;
    double p;
    double * table_manager_t_9;
    double * table_manager_p_9;
    int table_manager_n_9;
};
typedef struct _struct_particle _class_particle;

/* In McStas this function is generated by the runtime.  Outside McStas an
 * implementation must be provided (see test/particle_stub.c). */
void * particle_getvar_void(_class_particle * p, char * name, int * success);
#endif /* MCSTAS */

/* Aggregated histogram data for all recorders.
 * Arrays are row-major with shape [recorders][bins]. */
struct TableManagerData {
    int     recorders;
    int     bins;
    double  t_min;
    double  t_max;
    double * tp;   /* probability-weighted time sum  */
    double * p1;   /* probability sum                */
    double * p2;   /* squared-probability sum        */
    int    * n;    /* hit count                      */
};

/* --- Data lifetime --- */
struct TableManagerData * table_manager_data_alloc(int recorders, int bins,
                                                   double t_min, double t_max);
void table_manager_data_free(struct TableManagerData * data);

/* --- Global state lifetime --- */
void table_manager_state_alloc(void);
void table_manager_state_free(void);
int  table_manager_state_exists(void);
int  table_manager_state_add_recorder(const char * name, double distance);
void table_manager_state_finalize(int manager_index,
                                  const char * t_name,
                                  const char * p_name,
                                  const char * n_name);

/* --- Per-particle accessors (require a finalised state) --- */
double ** table_manager_particle_t_array_ptr(_class_particle * p);
double ** table_manager_particle_p_array_ptr(_class_particle * p);
int *     table_manager_particle_n_ptr(_class_particle * p);

/* --- Per-particle operations --- */
void table_manager_particle_alloc(_class_particle * p, double t_zero);
int  table_manager_particle_record(_class_particle * p, int recorder_index);
int  table_manager_particle_to_table(_class_particle * p,
                                     struct TableManagerData * data);
int  table_manager_particle_free(_class_particle * p);

/* --- JSON helpers (write to an already-open FILE) --- */
int table_manager_json_indent(FILE * f, int level);
int table_manager_json_array_double(FILE * f, double * x, int n);
int table_manager_json_array_int(FILE * f, int * x, int n);
int table_manager_json_array_string(FILE * f, char ** x, int n);
int table_manager_json_matrix_double(FILE * f, double * x, int m, int n,
                                     int indent_level);
int table_manager_json_matrix_int(FILE * f, int * x, int m, int n,
                                  int indent_level);

/* --- Output --- */
int table_manager_write_output_file(const char * filename,
                                    struct TableManagerData * data);

#endif /* TOF_TABLE_LIB_H */
